from __future__ import annotations

from dataclasses import dataclass

# Relevance notes name the migration concern. They are not exploit guidance
# and they are not a quantum-safety determination.

Q_PUBLIC_KEY = (
    "Public-key algorithms built on integer factorization or discrete logarithms "
    "are a post-quantum migration concern for signatures and key establishment. "
    "This inventory does not measure that risk for a live deployment."
)
Q_HASH_BROKEN = (
    "MD5 and SHA-1 are already unsuitable where collision resistance matters. "
    "That is a classical defect. Replacing them does not by itself add post-quantum protection."
)
Q_SYMMETRIC = (
    "Symmetric encryption is a different decision from replacing factorization-based key establishment. "
    "AES-256 is a common long-term choice while public-key migration is planned. "
    "This finding does not prove quantum safety."
)
Q_AES128 = (
    "AES-128 has a smaller margin against quantum search than AES-256. "
    "Treat the key length as an inventory and compatibility decision. "
    "This finding does not prove the algorithm is broken."
)
Q_TLS_OLD = (
    "TLS 1.0 and TLS 1.1 are deprecated. Disabling them is classical hardening. "
    "It does not make the connection post-quantum."
)
Q_TLS_CURRENT = (
    "TLS 1.2 and TLS 1.3 are current classical protocols. "
    "They still use quantum-vulnerable key establishment unless both peers negotiate a hybrid or post-quantum group."
)
Q_LIBRARY = (
    "A cryptographic library is a dependency to inventory. "
    "The package name does not establish which algorithms run in production, or whether the result is quantum-safe."
)
Q_PQC_NAME = (
    "A post-quantum algorithm name appeared. "
    "A name in source or configuration does not prove protocol integration, peer support, or quantum safety."
)
Q_CERT = (
    "Certificate key types and signature algorithms need their own migration plan. "
    "A parsed certificate describes this file only. It does not describe the whole estate."
)
Q_MAC = (
    "A message authentication code or JWT keyed with a symmetric secret depends on that secret's length and handling. "
    "This is an inventory item, not a quantum-safety result."
)
Q_PASSWORD = (
    "Password hashing is a classical credential-storage decision. "
    "It is not the same work as migrating public-key protocols."
)


@dataclass(frozen=True)
class Rule:
    rule_id: str
    pattern: str
    name: str
    kind: str
    usage: str
    concern: str
    summary: str
    migration_hint: str
    quantum_relevance: str
    tier: str = "strong"


def rules() -> list[Rule]:
    strong = [
        Rule(
            "py-hashlib-md5",
            r"\bhashlib\.md5\s*\(",
            "MD5",
            "algorithm",
            "hash",
            "urgent",
            "Python hashlib.md5 call.",
            "Replace collision-broken hashes in integrity and signature contexts with a hash the protocol still accepts, commonly SHA-256 or stronger, and add interoperability tests.",
            Q_HASH_BROKEN,
        ),
        Rule(
            "py-hashlib-sha1",
            r"\bhashlib\.sha1\s*\(",
            "SHA-1",
            "algorithm",
            "hash",
            "urgent",
            "Python hashlib.sha1 call.",
            "Retire SHA-1 where collision resistance matters. Confirm the replacement identifier with every verifier before changing stored values.",
            Q_HASH_BROKEN,
        ),
        Rule(
            "py-hashlib-sha256",
            r"\bhashlib\.sha256\s*\(",
            "SHA-256",
            "algorithm",
            "hash",
            "monitor",
            "Python hashlib.sha256 call.",
            "Keep SHA-256 on the inventory. It is not the first public-key migration item. Confirm the protocol's required hash before any change.",
            "SHA-256 remains a widely used classical hash. Inventory it so later protocol changes have an owner. This is not a quantum-safety claim.",
        ),
        Rule(
            "py-hashlib-sha512",
            r"\bhashlib\.sha512\s*\(",
            "SHA-512",
            "algorithm",
            "hash",
            "monitor",
            "Python hashlib.sha512 call.",
            "Record the caller and the protocol that expects SHA-512. No algorithm swap is implied.",
            "SHA-512 is a classical hash with a large output. Inventory it separately from public-key migration.",
        ),
        Rule(
            "py-pbkdf2-sha1",
            r"\bpbkdf2_hmac\s*\(\s*['\"]sha1['\"]",
            "PBKDF2-SHA-1",
            "algorithm",
            "password_hashing",
            "urgent",
            "PBKDF2 invoked with SHA-1.",
            "Move password storage to a password hashing function from a vetted library, with parameters chosen for the deployment, and plan a re-hash on next login.",
            Q_PASSWORD,
        ),
        Rule(
            "py-rsa-generate",
            r"\brsa\.generate_private_key\s*\(",
            "RSA",
            "algorithm",
            "keygen",
            "plan",
            "RSA private key generation through the cryptography API.",
            "Treat RSA key generation as a migration candidate for signatures or key establishment. A post-quantum replacement is not a drop-in for every protocol.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "py-rsa-key-size",
            r"\bkey_size\s*=\s*(1024|2048|3072|4096)\b",
            "RSA-key-size",
            "key_size",
            "keygen",
            "plan",
            "Explicit RSA key size.",
            "Record the size with the data it protects. Sizes under 2048 bits are classically weak as well as a migration concern. Larger RSA keys are still a post-quantum migration item.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "py-ec-p256",
            r"\bec\.SECP256R1\s*\(",
            "ECDSA-P-256",
            "algorithm",
            "signature",
            "plan",
            "P-256 elliptic curve constructor.",
            "Inventory P-256 as a classical signature or key-agreement parameter. Hybrid or post-quantum replacements need peer and certificate support.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "py-ec-p384",
            r"\bec\.SECP384R1\s*\(",
            "ECDSA-P-384",
            "algorithm",
            "signature",
            "plan",
            "P-384 elliptic curve constructor.",
            "Inventory P-384 with its verifiers. Curve changes and post-quantum signatures both require an interoperability matrix.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "py-ecdsa-api",
            r"\bec\.ECDSA\s*\(",
            "ECDSA",
            "algorithm",
            "signature",
            "plan",
            "ECDSA signer from the cryptography package.",
            "Inventory the curve used with this signer and the verifiers that must accept it.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "py-rsa-pss",
            r"\bpadding\.PSS\s*\(",
            "RSA-PSS",
            "algorithm",
            "signature",
            "plan",
            "RSA-PSS padding from the cryptography package.",
            "RSA-PSS is still RSA. Treat it as a signature migration candidate and test verifier support before any identifier change.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "py-hashes-sha256",
            r"\bhashes\.SHA256\s*\(",
            "SHA-256",
            "algorithm",
            "hash",
            "monitor",
            "SHA-256 constructor from the cryptography package.",
            "Record which signature or MAC uses this hash before changing it.",
            "SHA-256 is a classical hash. Inventory it separately from public-key migration.",
        ),
        Rule(
            "py-hashes-sha384",
            r"\bhashes\.SHA384\s*\(",
            "SHA-384",
            "algorithm",
            "hash",
            "monitor",
            "SHA-384 constructor from the cryptography package.",
            "Record which signature uses this hash before changing it.",
            "SHA-384 is a classical hash. Inventory it separately from public-key migration.",
        ),
        Rule(
            "py-aesgcm",
            r"\bAESGCM(?:\.generate_key)?\s*\(",
            "AES-GCM",
            "algorithm",
            "bulk_encryption",
            "monitor",
            "AES-GCM used through the cryptography package.",
            "Record the key length at the call site. Prefer reviewing AES-128 versus AES-256 as a compatibility choice, using the vetted library already in use.",
            Q_SYMMETRIC,
        ),
        Rule(
            "py-pycrypto-import",
            r"\bfrom\s+Crypto\b|\bimport\s+Crypto\b",
            "PyCrypto",
            "library",
            "library",
            "urgent",
            "Import of the PyCrypto package layout.",
            "Plan a move from PyCrypto to a maintained vetted library. Do not copy cipher code into the application.",
            Q_LIBRARY,
        ),
        Rule(
            "py-pycrypto-des",
            r"\bfrom\s+Crypto\.Cipher\s+import\s+DES\b",
            "DES",
            "algorithm",
            "bulk_encryption",
            "urgent",
            "DES imported from PyCrypto.",
            "Retire DES. Move the call to a vetted library and an AEAD construction the peers can read.",
            "DES is a deprecated classical cipher with a short key. Retiring it is not a post-quantum migration by itself.",
        ),
        Rule(
            "py-cryptography-import",
            r"\b(?:import\s+cryptography|from\s+cryptography)\b",
            "cryptography",
            "library",
            "library",
            "informational",
            "Import of the Python cryptography package.",
            "Inventory the algorithms this vetted OpenSSL binding is used for. The import itself is not evidence of quantum safety.",
            Q_LIBRARY,
        ),
        Rule(
            "py-jwt-import",
            r"\bimport\s+jwt\b|\bfrom\s+jwt\s+import\b",
            "PyJWT",
            "library",
            "library",
            "plan",
            "Python jwt import. Confirm which distribution provides it.",
            "Record the JWT alg values alongside the library. Verifiers often allow-list algorithm identifiers.",
            Q_LIBRARY,
        ),
        Rule(
            "js-md5",
            r"\bcreateHash\(\s*['\"]md5['\"]\s*\)",
            "MD5",
            "algorithm",
            "hash",
            "urgent",
            "Node.js crypto.createHash('md5').",
            "Replace MD5 in integrity contexts and retest every consumer of the digest.",
            Q_HASH_BROKEN,
        ),
        Rule(
            "js-sha1",
            r"\bcreateHash\(\s*['\"]sha1['\"]\s*\)",
            "SHA-1",
            "algorithm",
            "hash",
            "urgent",
            "Node.js crypto.createHash('sha1').",
            "Retire SHA-1 where collision resistance matters and confirm the new identifier with clients.",
            Q_HASH_BROKEN,
        ),
        Rule(
            "js-cryptojs-md5",
            r"\bCryptoJS\.MD5\s*\(",
            "MD5",
            "algorithm",
            "hash",
            "urgent",
            "CryptoJS MD5 call.",
            "Replace CryptoJS MD5 uses and pin the vetted library you keep.",
            Q_HASH_BROKEN,
        ),
        Rule(
            "js-cryptojs-sha1",
            r"\bCryptoJS\.SHA1\s*\(",
            "SHA-1",
            "algorithm",
            "hash",
            "urgent",
            "CryptoJS SHA1 call.",
            "Retire CryptoJS SHA-1 uses after verifier tests.",
            Q_HASH_BROKEN,
        ),
        Rule(
            "js-cryptojs-aes",
            r"\bCryptoJS\.AES\b",
            "AES",
            "algorithm",
            "bulk_encryption",
            "plan",
            "CryptoJS AES call. The mode and key length are not fully visible from this match.",
            "Open the call and record mode and key length. CryptoJS passphrase helpers are not a complete key-management design.",
            Q_AES128,
        ),
        Rule(
            "js-node-forge",
            r"""require\(\s*['\"]node-forge['\"]\s*\)|from\s+['\"]node-forge['\"]""",
            "node-forge",
            "library",
            "library",
            "plan",
            "node-forge import.",
            "Inventory node-forge and the algorithms it is asked to run. Prefer platform crypto or another vetted library for new work.",
            Q_LIBRARY,
        ),
        Rule(
            "js-crypto-js-import",
            r"""require\(\s*['\"]crypto-js['\"]\s*\)|from\s+['\"]crypto-js['\"]""",
            "crypto-js",
            "library",
            "library",
            "plan",
            "crypto-js import.",
            "Inventory crypto-js call sites. The package name alone does not identify the mode or key length.",
            Q_LIBRARY,
        ),
        Rule(
            "js-jsonwebtoken",
            r"""require\(\s*['\"]jsonwebtoken['\"]\s*\)|from\s+['\"]jsonwebtoken['\"]""",
            "jsonwebtoken",
            "library",
            "library",
            "plan",
            "jsonwebtoken import.",
            "Record allowed JWT algorithms in verifiers. A new alg value fails closed until every consumer is updated.",
            Q_LIBRARY,
        ),
        Rule(
            "java-md5",
            r"""MessageDigest\.getInstance\(\s*['\"]MD5['\"]\s*\)""",
            "MD5",
            "algorithm",
            "hash",
            "urgent",
            "Java MessageDigest MD5.",
            "Replace MD5 in integrity contexts and retest consumers.",
            Q_HASH_BROKEN,
        ),
        Rule(
            "java-sha1",
            r"""MessageDigest\.getInstance\(\s*['\"]SHA-1['\"]\s*\)""",
            "SHA-1",
            "algorithm",
            "hash",
            "urgent",
            "Java MessageDigest SHA-1.",
            "Retire SHA-1 where collision resistance matters.",
            Q_HASH_BROKEN,
        ),
        Rule(
            "java-desede",
            r"""Cipher\.getInstance\(\s*['\"]DESede(?:/[^'\"]*)?['\"]\s*\)""",
            "3DES",
            "algorithm",
            "bulk_encryption",
            "urgent",
            "Java Cipher DESede (3DES).",
            "Retire 3DES. Choose an AEAD construction from a vetted provider the platform already ships, then test padding and token formats with clients.",
            "3DES is a deprecated classical cipher. Retiring it is not a post-quantum migration by itself.",
        ),
        Rule(
            "java-des",
            r"""Cipher\.getInstance\(\s*['\"]DES(?:/[^'\"]*)?['\"]\s*\)""",
            "DES",
            "algorithm",
            "bulk_encryption",
            "urgent",
            "Java Cipher DES.",
            "Retire DES. Do not reimplement a block cipher in application code.",
            "DES is a deprecated classical cipher with a short key.",
        ),
        Rule(
            "java-aes",
            r"""Cipher\.getInstance\(\s*['\"]AES(?:/[^'\"]*)?['\"]\s*\)""",
            "AES",
            "algorithm",
            "bulk_encryption",
            "plan",
            "Java Cipher AES. Mode and key length depend on the transformation string.",
            "Record mode and key length. ECB and unauthenticated CBC need a design review that is separate from post-quantum key establishment.",
            Q_AES128,
        ),
        Rule(
            "go-md5",
            r"\bmd5\.(?:Sum|New)\s*\(",
            "MD5",
            "algorithm",
            "hash",
            "urgent",
            "Go crypto/md5 call.",
            "Replace MD5 in integrity contexts and retest consumers.",
            Q_HASH_BROKEN,
        ),
        Rule(
            "go-sha1",
            r"\bsha1\.(?:Sum|New)\s*\(",
            "SHA-1",
            "algorithm",
            "hash",
            "urgent",
            "Go crypto/sha1 call.",
            "Retire SHA-1 where collision resistance matters.",
            Q_HASH_BROKEN,
        ),
        Rule(
            "go-rsa-generate",
            r"\brsa\.GenerateKey\s*\(",
            "RSA",
            "algorithm",
            "keygen",
            "plan",
            "Go crypto/rsa key generation.",
            "Record the bit size and the protocol that consumes the key. RSA remains a post-quantum migration candidate.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "go-rsa-bits",
            r"\brsa\.GenerateKey\s*\([^)]*?\b(1024|2048|3072|4096)\b",
            "RSA-key-size",
            "key_size",
            "keygen",
            "plan",
            "Go RSA generation with an explicit bit size.",
            "Sizes under 2048 bits need classical retirement as well as a place on the migration list.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "go-import-md5",
            r'"crypto/md5"',
            "crypto/md5",
            "library",
            "library",
            "urgent",
            "Go import of crypto/md5.",
            "Confirm whether the import is still used for integrity. Prefer retiring the dependency path with the call sites.",
            Q_LIBRARY,
        ),
        Rule(
            "go-import-sha1",
            r'"crypto/sha1"',
            "crypto/sha1",
            "library",
            "library",
            "urgent",
            "Go import of crypto/sha1.",
            "Retire SHA-1 call sites and then drop the import.",
            Q_LIBRARY,
        ),
        Rule(
            "go-import-rsa",
            r'"crypto/rsa"',
            "crypto/rsa",
            "library",
            "library",
            "plan",
            "Go import of crypto/rsa.",
            "Map which commands generate or trust RSA keys before choosing a migration pattern.",
            Q_LIBRARY,
        ),
        Rule(
            "tls-1-0-token",
            r"(?<![\w.])TLSv1\.0(?![\w.])|(?<![\w.])TLSv1(?![\w.\d])",
            "TLS 1.0",
            "protocol",
            "transport",
            "urgent",
            "TLS 1.0 token in source or configuration.",
            "Remove TLS 1.0 after checking the oldest supported client. This is classical hardening, not post-quantum protection.",
            Q_TLS_OLD,
        ),
        Rule(
            "tls-1-0-python",
            r"\bssl\.PROTOCOL_TLSv1\b(?!_)",
            "TLS 1.0",
            "protocol",
            "transport",
            "urgent",
            "Python ssl.PROTOCOL_TLSv1.",
            "Stop constructing TLS 1.0 contexts. Use a current protocol constant and set an explicit minimum after client testing.",
            Q_TLS_OLD,
        ),
        Rule(
            "tls-1-1-token",
            r"(?<![\w.])TLSv1\.1(?![\w.])|\bssl\.PROTOCOL_TLSv1_1\b",
            "TLS 1.1",
            "protocol",
            "transport",
            "urgent",
            "TLS 1.1 token.",
            "Remove TLS 1.1 after client testing. This does not add post-quantum key establishment.",
            Q_TLS_OLD,
        ),
        Rule(
            "tls-1-2-token",
            r"(?<![\w.])TLSv1\.2(?![\w.])|\bssl\.PROTOCOL_TLSv1_2\b",
            "TLS 1.2",
            "protocol",
            "transport",
            "plan",
            "TLS 1.2 token.",
            "TLS 1.2 can stay during a transition, but cipher suites and key establishment still need an inventory. Hybrid groups are a later, explicit change.",
            Q_TLS_CURRENT,
        ),
        Rule(
            "tls-1-3-token",
            r"(?<![\w.])TLSv1\.3(?![\w.])|\bssl\.PROTOCOL_TLSv1_3\b",
            "TLS 1.3",
            "protocol",
            "transport",
            "plan",
            "TLS 1.3 token.",
            "TLS 1.3 is current classical practice. It is not post-quantum unless a hybrid or post-quantum group is configured and mutually supported.",
            Q_TLS_CURRENT,
        ),
        Rule(
            "tls-min-10",
            r"minVersion[\"']?\s*[:=]\s*[\"']1\.0[\"']",
            "TLS 1.0",
            "protocol",
            "transport",
            "urgent",
            "Configured minimum TLS version 1.0.",
            "Raise the minimum only after an interoperability test with the supported clients. Document the rollback.",
            Q_TLS_OLD,
        ),
        Rule(
            "tls-min-11",
            r"minVersion[\"']?\s*[:=]\s*[\"']1\.1[\"']",
            "TLS 1.1",
            "protocol",
            "transport",
            "urgent",
            "Configured minimum TLS version 1.1.",
            "Raise the minimum after client testing.",
            Q_TLS_OLD,
        ),
        Rule(
            "openssl-min-protocol-10",
            r"MinProtocol\s*=\s*(?:TLSv1\.0|TLSv1)(?![\w.])",
            "TLS 1.0",
            "protocol",
            "transport",
            "urgent",
            "OpenSSL MinProtocol allows TLS 1.0.",
            "Raise MinProtocol after client testing. Security level and cipher string should be reviewed in the same change window.",
            Q_TLS_OLD,
        ),
        Rule(
            "openssl-seclevel-0",
            r"SECLEVEL\s*=\s*0\b",
            "OpenSSL security level 0",
            "protocol",
            "transport",
            "urgent",
            "OpenSSL security level 0 permits very weak parameters.",
            "Raise the security level in a staged rollout. This setting is a classical configuration defect.",
            "Security level 0 is a deprecated configuration. Changing it does not prove quantum safety.",
        ),
        Rule(
            "sslv3",
            r"\bSSLv3\b|\bssl\.PROTOCOL_SSLv3\b",
            "SSL 3.0",
            "protocol",
            "transport",
            "urgent",
            "SSL 3.0 reference.",
            "Remove SSL 3.0. There is no post-quantum meaning to keeping it.",
            "SSL 3.0 is obsolete. This is a classical protocol defect.",
        ),
        Rule(
            "rc4",
            r"\bRC4(?:-SHA)?\b",
            "RC4",
            "algorithm",
            "bulk_encryption",
            "urgent",
            "RC4 cipher reference.",
            "Remove RC4 from cipher lists and retest handshake compatibility.",
            "RC4 is a deprecated classical stream cipher.",
        ),
        Rule(
            "aes128-sha-suite",
            r"\bAES128-SHA\b",
            "TLS AES128-SHA",
            "algorithm",
            "transport",
            "urgent",
            "TLS cipher suite using AES-128 and SHA-1 (AES128-SHA).",
            "Drop this suite when clients allow a current AEAD suite. Confirm the replacement in staging.",
            "This suite couples an older MAC with classical key establishment. Retiring it is not by itself a post-quantum migration.",
        ),
        Rule(
            "rsa-key-transport",
            r"\bTLS_RSA_WITH_[A-Z0-9_]+\b",
            "RSA key transport",
            "algorithm",
            "key_agreement",
            "urgent",
            "TLS cipher suite using static RSA key transport.",
            "Prefer suites with ephemeral key establishment, then plan hybrid key establishment separately for long-lived confidentiality.",
            "RSA key transport is deprecated in TLS and is a harvest-now-decrypt-later concern if traffic or stored sessions must stay confidential.",
        ),
        Rule(
            "ecdhe-rsa",
            r"\bECDHE-RSA\b",
            "ECDHE-RSA",
            "algorithm",
            "key_agreement",
            "plan",
            "Ephemeral elliptic-curve Diffie-Hellman authenticated with RSA.",
            "Inventory the curve and the certificate algorithm. Classical ECDHE is still a post-quantum migration candidate for long-lived confidentiality.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "aes128-gcm",
            r"\bAES128-GCM\b|\bA128GCM\b|\bAES-128-GCM\b",
            "AES-128-GCM",
            "algorithm",
            "bulk_encryption",
            "plan",
            "AES-128-GCM reference.",
            "Record where AES-128-GCM is required by peers. A move to AES-256-GCM is a compatibility change, not a finished post-quantum program.",
            Q_AES128,
        ),
        Rule(
            "aes256-gcm",
            r"\bAES256-GCM\b|\bA256GCM\b|\bAES-256-GCM\b",
            "AES-256-GCM",
            "algorithm",
            "bulk_encryption",
            "monitor",
            "AES-256-GCM reference.",
            "Keep the suite on the inventory and confirm both peers actually negotiate it.",
            Q_SYMMETRIC,
        ),
        Rule(
            "a128cbc-hs256",
            r"\bA128CBC-HS256\b",
            "AES-128-CBC-HMAC-SHA-256",
            "algorithm",
            "bulk_encryption",
            "plan",
            "JOSE content encryption A128CBC-HS256.",
            "Confirm every decryptor before changing the enc value. CBC plus HMAC is a classical JOSE construction, not a post-quantum KEM.",
            Q_AES128,
        ),
        Rule(
            "jwt-hs256",
            r"\balgorithm\s*[:=]\s*['\"]HS256['\"]|['\"]HS256['\"]",
            "HMAC-SHA-256",
            "algorithm",
            "mac",
            "monitor",
            "JWT or JOSE HMAC-SHA-256 (HS256).",
            "Inventory who shares the symmetric secret. Rotating the secret is a different project from post-quantum signatures.",
            Q_MAC,
        ),
        Rule(
            "jwt-rs256",
            r"\balgorithm\s*[:=]\s*['\"]RS256['\"]|['\"]RS256['\"]",
            "RS256",
            "algorithm",
            "signature",
            "plan",
            "JWT RS256 (RSASSA-PKCS1-v1_5 with SHA-256).",
            "Verifiers must allow-list algorithms. A post-quantum or composite signature will need a new identifier and updated consumers.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "jwt-es256",
            r"['\"]ES256['\"]",
            "ES256",
            "algorithm",
            "signature",
            "plan",
            "JWT ES256 (ECDSA P-256 with SHA-256).",
            "Treat ES256 as classical ECDSA. Plan verifier updates before any algorithm identifier change.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "jwt-none",
            r"\balgorithm\s*[:=]\s*['\"]none['\"]",
            "JWT none",
            "algorithm",
            "signature",
            "urgent",
            "JWT alg none.",
            "Reject unsigned tokens in verifiers. This is a classical authentication defect.",
            "Unsigned tokens do not provide integrity. This finding is not a post-quantum result.",
        ),
        Rule(
            "ssh-rsa",
            r"\bssh-rsa\b",
            "ssh-rsa",
            "algorithm",
            "signature",
            "urgent",
            "SSH public-key algorithm ssh-rsa (SHA-1 based).",
            "Move hosts and clients to current SSH signature algorithms and test existing authorized_keys entries.",
            "ssh-rsa is deprecated in current OpenSSH defaults because of SHA-1. That retirement is classical hardening.",
        ),
        Rule(
            "ssh-dh-sha1",
            r"\bdiffie-hellman-group(?:1|14)-sha1\b",
            "SSH Diffie-Hellman SHA-1",
            "algorithm",
            "key_agreement",
            "urgent",
            "SSH key exchange using a SHA-1 group.",
            "Remove these key exchange names after checking existing clients. Classical DH is also a post-quantum migration candidate.",
            Q_PUBLIC_KEY,
        ),
        Rule(
            "openssl-rsa-bits",
            r"\brsa:(1024|2048|3072|4096)\b",
            "RSA-key-size",
            "key_size",
            "keygen",
            "plan",
            "OpenSSL-style RSA bit size.",
            "Record the size and where the generated key is installed.",
            Q_PUBLIC_KEY,
        ),
    ]
    weak = [
        Rule(
            "weak-rsa",
            r"\bRSA\b",
            "RSA",
            "algorithm",
            "unknown",
            "plan",
            "RSA mentioned without a confirmed API or configuration pattern on this line.",
            "Confirm whether this mention generates keys, verifies signatures, or is only discussion. Uncertain matches stay off the critical path until confirmed.",
            Q_PUBLIC_KEY,
            tier="weak",
        ),
        Rule(
            "weak-aes",
            r"\bAES\b",
            "AES",
            "algorithm",
            "unknown",
            "monitor",
            "AES mentioned without a confirmed mode, key length, or API on this line.",
            "Open the surrounding code or configuration before scheduling work.",
            Q_AES128,
            tier="weak",
        ),
        Rule(
            "weak-md5",
            r"\bMD5\b",
            "MD5",
            "algorithm",
            "unknown",
            "urgent",
            "MD5 mentioned without a confirmed API on this line.",
            "Confirm a real call site before treating this as a defect.",
            Q_HASH_BROKEN,
            tier="weak",
        ),
        Rule(
            "weak-sha1",
            r"\bSHA-1\b|\bSHA1\b",
            "SHA-1",
            "algorithm",
            "unknown",
            "urgent",
            "SHA-1 mentioned without a confirmed API on this line.",
            "Confirm a real call site before treating this as a defect.",
            Q_HASH_BROKEN,
            tier="weak",
        ),
        Rule(
            "weak-ecdsa",
            r"\bECDSA\b",
            "ECDSA",
            "algorithm",
            "unknown",
            "plan",
            "ECDSA mentioned without a confirmed curve or API on this line.",
            "Confirm the curve and the verifier set if this is a real signature use.",
            Q_PUBLIC_KEY,
            tier="weak",
        ),
        Rule(
            "weak-mlkem",
            r"\bML-KEM(?:-\d+)?\b|\bKyber\d*\b",
            "ML-KEM",
            "algorithm",
            "unknown",
            "informational",
            "ML-KEM or Kyber mentioned without a confirmed implementation API on this line.",
            "Confirm a vetted library and mutual peer support. A name is not a quantum-safe deployment.",
            Q_PQC_NAME,
            tier="weak",
        ),
        Rule(
            "weak-mldsa",
            r"\bML-DSA(?:-\d+)?\b|\bDilithium\d*\b",
            "ML-DSA",
            "algorithm",
            "unknown",
            "informational",
            "ML-DSA or Dilithium mentioned without a confirmed implementation API on this line.",
            "Confirm certificate, HSM, and verifier support. A name is only an inventory hit.",
            Q_PQC_NAME,
            tier="weak",
        ),
        Rule(
            "weak-slh",
            r"\bSLH-DSA\b|\bSPHINCS\+?\b",
            "SLH-DSA",
            "algorithm",
            "unknown",
            "informational",
            "SLH-DSA or SPHINCS+ mentioned without a confirmed implementation API on this line.",
            "Confirm verifier support and object sizes with a vetted library before planning a cutover.",
            Q_PQC_NAME,
            tier="weak",
        ),
    ]
    return strong + weak
