apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: billing
  annotations:
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1 TLSv1.2"
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-RSA-AES128-GCM-SHA256"
spec:
  tls:
    - hosts:
        - billing.example.invalid
